### ISSUE TITLE
missing file `toolbox.json`

### ISSUE THREAD

**Issue by altesockensuppe** [jope82/sys-clk-uncapped-gpu-and-other-extras#12]
The Version 2.0.0 work's as expected!

But, i need to add the file `toolbox.json` in to: `/atmosphere/contents/00FF0000636C6BFF/` to have the entry in the Tesla menu.

The file contains:
```
{
    "name": "00FF0000636C6BFF",
    "requires_reboot": true,
    "tid": "00FF0000636C6BFF"
}
```

**Comment by jope82** [comment]
That file should not be needed for sys-clk, see https://github.com/retronx-team/sys-clk/issues/48
