### ISSUE TITLE
request: max memory clocks for all games

### ISSUE THREAD

**Issue by mc711** [jope82/sys-clk-uncapped-gpu-and-other-extras#4]
since the memory clock has the least effect on battery, it would be nice to have a max memory clock option for all games option if possible...

**Comment by jope82** [comment]
Good idea. I think I will implement a switch that will make the temporary overrides permanent. With that you could set the mem clock (and cpu + gpu) globally.

**Comment by jope82** [comment]
This is now implemented in the new release 1.0.2_b, added option to override MEM permanently to 1600 MHz (or whatever your max clock is). Also added an option to make a global default profile for applications without an application specific profile via sys-clk manager. With this you can also set permanent global overrides if there are no application profiles at all.
