### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Medel87** [jope82/sys-clk-uncapped-gpu-and-other-extras#5]
Sorry, this is not an issue, but I don't know how to contact you, it's possible you make a version of KazushiMe's OC Suite with no GPU limit for Erista? it will be great

**Comment by jope82** [comment]
I’m not familiar with OC Suite but with my fork there is no GPU limit if you use the ”Uncapped GPU” option. For example you can set GPU to 921 while in handheld but it will make your Switch sleep soon because the power draw is so high. Not wise to do that but the option to do it already exists.

**Comment by Medel87** [comment]
Yes, I know, I used your sysclk combined with RAM OC long ago, with caution about power draw, and no problem, thanks for this, but OC Suite have ram OC included, and a new governor that scale up/down frequencies when needed, and it's really cool, thanks anyway mate

**Comment by jope82** [comment]
Ah, okay. Weird that they are limiting GPU in that suite, I thought it would max out everything, lol. At least 768 in handheld should be okay to do with Erista, 921 is too much. At the moment I have no time to look into that suite but maybe some day.

**Comment by Medel87** [comment]
I think the same, because 1020/768 have similar power draw like 1768/460, I only use 921 while docked, or handheld with official charger.

Thanks for answer, if someday you have time and take a look, it will be great, regards
