### ISSUE TITLE
Request to add new features

### ISSUE THREAD

**Issue by lsp199308** [jope82/sys-clk-uncapped-gpu-and-other-extras#6]
Very sorry to bother you, is it possible to add docked mode.
For example, if you set docked mode in ReverseNX-RT plugin, sysclk automatically adjusts to cpu 1020 gpu 768 mem 1600, thank you very much.

**Comment by jope82** [comment]
No worries. I was planning to add this feature in the past but didn’t like how it worked so I left it out. I might look into it again. I use also ReverseNX for some games and I just use Uncapped GPU = Yes and I put cpu 1020, gpu 768 and mem 1600 to the game’s Handheld profile. Of course it doesn’t change real-time but I want to keep those games Docked at all times so I’m fine with ”hard-coded” values.

**Comment by lsp199308** [comment]
Sorry, but if the game docked frequency is set in /config/sys-clk/config.ini and ReverseNX-RT sets docked, can sysclk read this config.ini configuration frequency instead of inserting it into the official docked
For example

[01007EF00011E000]
docked_cpu=1224
docked_gpu = 768
docked_MEM=1600
handheld_charging_cpu=1224
handheld_mem=1600
sysclk only needs to read the docked value in config.ini, while keeping the handheld frequency

**Comment by jope82** [comment]
Sure, but it needs of course extra logic to read the state of ReverseNX. Otherwise setting ReverseNX to Docked won’t do anything in sys-clk.
